name: Docker Build And Deploy

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Azure Container Registry Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Get commit hash
      id: get-commit-hash
      run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
    - name: Get timestamp
      id: get-timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d-%H%M')"
          
    - name: 'Build KedaWorker'
      env:
        IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
      run: |
        cd KedaWorker
        # docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:latest .
        # docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:${{ github.sha }}

        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:$IMAGE_TAG -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:latest .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:$IMAGE_TAG
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:latest
    - run: |
        docker images
