name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Azure Container Registry Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Build KedaWorker'
      run: |
        cd KedaWorker
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kedaworker:${{ github.sha }}
    - run: |
        docker images
